server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false

spring:
  application:
    name: spring-cloud-8001
  output:
    ansi:
      enabled: always

feign:
  hystrix:
    enabled: true

rocketmq:
  consumer:
    isOnOff: on
    groupName: spring-cloud-8001
    namesrvAddr: 119.45.127.27:9876
    topics: DemoTopic
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1


